# Site Info
title: 'Spirit&#39;s Dev Blog'
tagline: 'Spirit&#39;s Dev Blog'
description: '프로그래밍을 공부하며 배운점 느낀점을 기록하는 곳입니다.'
baseurl: ""
url: https://tjsry0466.github.io
logo: '/assets/images/kyojs.png'
future: true
# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: JEONG SEONKYO
  description: Spirit(JEONG SEONKYO)
  contact:
    # linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/tjsry0466
    facebook:  https://www.facebook.com/seonkyos
    # twitter:   https://twitter.com/Li_Zhihao
    # weibo:     http://weibo.com/41173780
    email:    tjs0466@naver.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/blog/'
  Categories:
    - '/'
    # - { Categories All: '/blog/categories/' }
    - { TIL (Today I Learned): '/blog/categories/#til' }
    - { Project : '/blog/categories/#project' }
    #- { 컴퓨터공학 : '/blog/categories/#컴퓨터공학' }
    - { Django: '/blog/categories/#django' }
    - { DB : '/blog/categories/#DB' }
    - { python: '/blog/categories/#python' }
    - { vue.js : '/blog/categories/#vuejs' }
    - { JavaScript: '/blog/categories/#javascript' }
    - { Coding Guide: '/blog/categories/#codingguide' }
    - { jQuery: '/blog/categories/#jquery' }
    #- { MySQL: '/blog/categories/#MySQL' }
    #- { 알고리즘 문제풀이: '/blog/categories/#알고리즘-문제풀이' }
    - { git: '/blog/categories/#git' }
    - { flutter: '/blog/categories/#flutter' }
    #- { firebase: '/blog/categories/#firebase' }
    #- { etc: '/blog/categories/#etc' }
    # - { Tags: '/blog/tags/' }
    - { DataBase: '/blog/categories/#database' }
    - { OS(operating system): '/blog/categories/#os'}
    - { Docker: '/blog/categories/#docker'}
  About:
    - '/about/'
  Search:
    - '/search/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'


# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-92094009-1' # leave blank if you don't want google analytics
disqus_short_name: 'https-tjsry0466-github-io' # leave blank if you don't want disqus


# Use the following plug-ins
gems:
  - jekyll-paginate
